### ISSUE TITLE
Allow to read the patch from a file

### ISSUE THREAD

**Issue by panglesd** [panglesd/diffcessible#3]
Currently, the executable read a file from a hardcoded path: `"diff.example"`.

We need to be able to pass the file on the command line. This would be a required argument to the command line.

**Comment by yokurang** [comment]
Hi, I have a local fork of the repository on my machine and would like to try this:

![image](https://github.com/panglesd/diffcessible/assets/114996150/fc35e005-153f-4b12-afac-8033bf629afb)

**Comment by panglesd** [comment]
Yes, let this issue be assigned to you!

**Comment by yokurang** [comment]
Hi @panglesd, I just made a pull request for this issue: https://github.com/panglesd/diffcessible/pull/22

In my solution, I added a flag to accept the patch file as a command line argument instead of having to specify the file name as a positional argument for a better user experience. I decided on the flag `--file` since I thought it was the most intuitive. Please let me know if you have any comments.

Cheers,
yokurang
